<?php

echo '                         <option value="" data-class="blank"></option>' . PHP_EOL;
echo '                         <option value="Big Key" data-class="big_key">Big Key</option>' . PHP_EOL;
echo '                         <option value="Bombos" data-class="bombos">Bombos</option>' . PHP_EOL;
echo '                         <option value="Bombs" data-class="bombs">Bombs</option>' . PHP_EOL;
echo '                         <option value="Book" data-class="book">Book</option>' . PHP_EOL;
echo '                         <option value="Boomerang" data-class="boomerang">Boomerang</option>' . PHP_EOL;
echo '                         <option value="Boots" data-class="boots">Boots</option>' . PHP_EOL;
echo '                         <option value="Bow" data-class="bow">Bow</option>' . PHP_EOL;
echo '                         <option value="Bugnet" data-class="bugnet">Bug Net</option>' . PHP_EOL;
echo '                         <option value="Cape" data-class="cape">Cape</option>' . PHP_EOL;
echo '                         <option value="Compass" data-class="compass">Compass</option>' . PHP_EOL;
echo '                         <option value="Empty Bottle" data-class="empty_bottle">Empty Bottle</option>' . PHP_EOL;
echo '                         <option value="Ether" data-class="ether">Ether</option>' . PHP_EOL;
echo '                         <option value="Flippers" data-class="flippers">Flippers</option>' . PHP_EOL;
echo '                         <option value="Flute" data-class="flute">Flute</option>' . PHP_EOL;
echo '                         <option value="Gloves" data-class="gloves">Gloves</option>' . PHP_EOL;
echo '                         <option value="Green Potion" data-class="green_potion">Green Potion</option>' . PHP_EOL;
echo '                         <option value="Hammer" data-class="hammer">Hammer</option>' . PHP_EOL;
echo '                         <option value="Heart" data-class="heart">Heart</option>' . PHP_EOL;
echo '                         <option value="Hookshot" data-class="hookshot">Hookshot</option>' . PHP_EOL;
echo '                         <option value="Ice Rod" data-class="ice_rod">Ice Rod</option>' . PHP_EOL;
echo '                         <option value="Lamp" data-class="lamp">Lamp</option>' . PHP_EOL;
echo '                         <option value="Magic Powder" data-class="magic_powder">Magic Powder</option>' . PHP_EOL;
echo '                         <option value="Map" data-class="map">Map</option>' . PHP_EOL;
echo '                         <option value="Mirror" data-class="mirror">Mirror</option>' . PHP_EOL;
echo '                         <option value="Moon Pearl" data-class="moon_pearl">Moon Pearl</option>' . PHP_EOL;
echo '                         <option value="Mushroom" data-class="mushroom">Mushroom</option>' . PHP_EOL;
echo '                         <option value="Pendant" data-class="pendant">Pendant</option>' . PHP_EOL;
echo '                         <option value="Quake" data-class="quake">Quake</option>' . PHP_EOL;
echo '                         <option value="Shield" data-class="shield">Shield</option>' . PHP_EOL;
echo '                         <option value="Shovel" data-class="shovel">Shovel</option>' . PHP_EOL;
echo '                         <option value="Somaria" data-class="somaria">Somaria</option>' . PHP_EOL;
echo '                         <option value="Tunic" data-class="tunic">Tunic</option>' . PHP_EOL;
