        <form method="post" autocomplete="off" action="<?= $domain ?>/editresult/<?= $result_id ?>">
            <table class="createAsync">
                <caption>Edit Result for <?= $racer_name ?><br /><?= $race_slug ?></caption>
<?php if ($race_team_flag == 'y') {
    echo '                <tr><td><label for"racerTeam" title="Editing this will update the team name for both team members.">Your Team: </label></td><td><input type="text" id="racerTeam" name="racerTeam" value ="' . $racer_team . '" /></td></tr>' . PHP_EOL;
}
?>
                <tr><td><label for="racerForfeit">Check to Forfeit: </label></td><td><input type="checkbox" id="racerForfeit" name="racerForfeit" value="y" <?php if ($racer_forfeit == 'y') { echo 'checked '; } ?>onclick="if (this.checked) { document.getElementsByClassName('timeInput')[0].style.display = 'none'; document.getElementsByClassName('timeInput')[1].style.display = 'none'; document.getElementsByClassName('timeInput')[2].style.display = 'none'; } else { document.getElementsByClassName('timeInput')[0].style.display = 'table-row'; document.getElementsByClassName('timeInput')[1].style.display = 'table-row'; document.getElementsByClassName('timeInput')[2].style.display = 'table-row'; }" /></td></tr>
                <tr class="timeInput"<?php if ($racer_forfeit == 'y') { echo ' style="display: none;"'; } ?>><td><label for="racerRTHours" title="Your actual time, *not* the time on the credits screen.">Your Real Time: </label></td><td><input type="number" id="racerRTHours" name="racerRTHours" min="0" max="24" placeholder="HH"<?php if (isset ($racerRTHours)) { echo ' value ="' . $racerRTHours . '"'; } ?> />:<input type="number" id="racerRTMinutes" name="racerRTMinutes" min="0" max="59" placeholder="MM"<?php if (isset ($racerRTMinutes)) { echo ' value ="' . $racerRTMinutes . '"'; } ?> />:<input type="number" id="racerRTSeconds" name="racerRTSeconds" min="0" max="59" placeholder="SS"<?php if (isset ($racerRTSeconds)) { echo ' value ="' . $racerRTSeconds . '"'; } ?> /></td></tr>
                <tr class="timeInput"<?php if ($racer_forfeit == 'y') { echo ' style="display: none;"'; } ?>><td><label for="racerCR" title="Your collected checks from the credits screen.">Your Collection Rate: </label></td><td><input class="CR" type="number" id="racerCR" name="racerCR" min="0"<?php if ($racer_collection_rate != null) { echo ' value ="' . $racer_collection_rate . '"'; } ?> /></td></tr>
                <tr><td><label for="racerComments">Comments: </label></td><td><input type="text" id="racerComments" name="racerComments"<?php if ($racer_comment != null) { echo ' value ="' . $racer_comment . '"'; } ?> /></td></tr>
                <tr><td><label for="racerVOD" title="Provide a full link to your VOD, starting with https://.">Link to VOD: </label></td><td><input type="text" id="racerVOD" name="racerVOD"<?php if ($racer_vod != null) { echo ' value ="' . $racer_vod . '"'; } if ($race_vod_flag == 'y') { echo ' required'; } ?> /></td></tr>
                <tr><td class="submitButton"><input type="Submit" class="submitButton" value="Edit Result" /></td><td class="submitButton"><a href="<?= $domain ?>/yourresults" class="fakeButton">Go Back</a></td></tr>
            </table>
        <input type="hidden" id="raceSlug" name="raceSlug" value="<?= $race_slug ?>" /><input type="hidden" id="racerName" name="racerName" value="<?= $racer_name ?>" />
        </form>